### ISSUE TITLE
To-do list after April CM (short term)

### ISSUE THREAD

**Issue by kirsty-duffy** [kirsty-duffy/uB-CC1pi#23]
- [x] Sort out mrb issue so we can actually process stuff (start by adding in packages one at a time to track down where the problem is coming from)
- [x] Find a workaround for the art bug causing the above issue
- [ ] Check the FV we're using (and that Marco's using). Assuming we need to do anything with it ourselves (I think we should just be able to use Marco's code now), switch to using the geometry service instead of hardcoded numbers.
- [x] Add stacked histograms of longest/second-longest/etc MIP-like and not-MIP-like tracks so we can see what we're selecting as "muon candidate" etc. Probably the easiest way to do this is to make a std::pair of track length and index in the original track length vector - then we can sort that based on track length and use the pair.second to get the index in other vectors
- [x] Look at momentum, either with similar plots to the above, or just in 1D (the highest/etc momenta by PDG, but not considering the MIP status), or both?
- [x] Sometimes a track isn't made despite us requesting one. We shouldn't allow these PFPs to be daughters, even if the original shower technically is. Maybe add a longer-term issue that we should understand what's going on here?
- [x] Add cut on distance between vertex and track start
- [x] PID (Kirsty): change deposited energy to use calibrated dEdx (hopefully can steal code from Andy F)
- [x] Investigate PID cuts: make 2D efficiency and purity plots as a function of neg2LLmuMIPminusp and (deposited energy - energy from length if proton) to see if the second cut can help us
- [x] Also make efficiency and purity plots as a function of cut on neg2LLp (see if this is any better than the subtraction one)
- [x] More PID investigation (Kirsty) - make data/MC comparisons for all variables we're considering cutting on to check that data/MC agreement is good. If not, we shouldn't cut there.
- [ ] Consider track length as a second MIP classification variable (though be careful, since this is probably model dependent)
- [x] Look at some event displays
